### ISSUE TITLE
Add my color scheme?

### ISSUE THREAD

**Issue by ryanseys** [bnb/awesome-hyperterm#1]
Not sure if it's "awesome" but I made a theme with my favourite colors: 

https://github.com/ryanseys/hyperterm-colors

**Comment by ryanseys** [comment]
It is also available on npm: https://www.npmjs.com/package/hyperterm-colors

**Comment by bnb** [comment]
Like it! Only suggestion is to write a command to show what the text displays like in the editor! 

Would have added 5 minutes ago, but Fastly's SSL Cert (for GitHub) was screwing up with my wireless. Anyway, added now!

**Comment by bnb** [comment]
@ryanseys Changed link to correct npm link!

**Comment by ryanseys** [comment]
Updated the screenshot. Nothing fancy with the text, just the same as the cursor color :)

**Comment by bnb** [comment]
@ryanseys Looks good! 👍
