### ISSUE TITLE
hyperterm-base16-ocean-saturated

### ISSUE THREAD

**Issue by henrikdahl** [bnb/awesome-hyperterm#101]
Figured I would share my saturated base16 dark ocean theme. Would be great if others find use for it!
Thanks!

https://github.com/henrikdahl/hyperterm-base16-ocean-saturated
https://www.npmjs.com/package/hyperterm-base16-ocean-saturated

**Comment by matheuss** [comment]
Would you mind sending a PR? 😄

**Comment by henrikdahl** [comment]
Just did. Thanks ✌️
