### ISSUE TITLE
HTYT : Search and play youtube videos in hyperterm

### ISSUE THREAD

**Issue by abhishekjairath** [bnb/awesome-hyperterm#105]
Repo : [https://github.com/abhishekjairath/htyt](https://github.com/abhishekjairath/htyt)
npm : [https://www.npmjs.com/package/htyt](https://www.npmjs.com/package/htyt)

Does it pass the awesome test? 😬

**Comment by matheuss** [comment]
I think it does! 😄 A PR is welcome 😌

**Comment by abhishekjairath** [comment]
#106

**Comment by abhishekjairath** [comment]
Made a pull request  #106. But the build failed.

**Comment by matheuss** [comment]
@abhishekjairath don't worry, the bot is crazy 😛
