### ISSUE TITLE
Add hyperblue?

### ISSUE THREAD

**Issue by tylerreckart** [bnb/awesome-hyperterm#17]
Converted my standard terminal layout over to a hyperterm theme. Other people might like it 😄 

https://github.com/tylerreckart/hyperblue

**Comment by bnb** [comment]
Hey @tylerreckart! Thanks for submitting your theme! 

Would you be able to make your image work on npm as well? The image is local to the GitHub repo and not pulling into npm correctly. Currently: https://www.npmjs.com/package/hyperblue

[RawGit](http://rawgit.com/) does the trick - paste your image into the big textarea and use the "Production" version in your repo.

**Comment by tylerreckart** [comment]
@bnb Added it in 👍

**Comment by tylerreckart** [comment]
Closed issue and migrated to a PR for easier integration into repo
