### ISSUE TITLE
Add Hyperterminator + Atom One Theme?

### ISSUE THREAD

**Issue by Snazzyham** [bnb/awesome-hyperterm#21]
There are these 2 awesome themes I found and noticed they weren't on the list. 

Theme 1 : [Hyperterminator](https://github.com/jxnblk/hyperterminator) by [Brent Jackson](http://github.com/jxnblk)
Theme 2 : [Atom One](https://github.com/mdo/hyperterm-atom-dark) by [Mark Otto](http://github.com/mdo)

**Comment by bnb** [comment]
Hyperterminator doesn't seem to quite fit "awesome". It's seemingly just one color change, with not much behind it. If multiple people request it to be added, I will - but at this point I don't think it fits the goal of the list.

With regard to the Atom theme, look at the first theme listed in the [themes list](https://github.com/bnb/awesome-hyperterm#themes) 🎉 😉 🎉
