### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by ReadmeCritic** [bnb/awesome-hyperterm#33]
Delightful Hpyerterm packages and resources
should be
Delightful HyperTerm packages and resources

Thanks!

PS: you could also add a space between the emoji and Delightful, would be 💯

**Comment by bnb** [comment]
There are actually several instances of this - thanks for pointing it out!

**Comment by bnb** [comment]
Ah, actually misunderstood what the typo was. Dyslexia 🙄

Looks like there is a space there to me - could you give a screenshot or copy and paste of what you mean?

**Comment by ReadmeCritic** [comment]
Looks good
Thanks
