### ISSUE TITLE
HYPERZSH: A zsh prompt for HyperTerm

### ISSUE THREAD

**Issue by tylerreckart** [bnb/awesome-hyperterm#51]
I'm not sure how this would fall into the fold here, but I configured a prompt especially for HyperTerm, so I figured that I'd at least give it a shot. Here's the repository: https://github.com/tylerreckart/hyperzsh

Thoughts?

**Comment by bnb** [comment]
Apologies for the tardy response - been crazy busy for Node Summit.

Since you can't install it by adding it to the plugins list in Hyperterm, I'd say it's a resource. Really awesome though - definitely worth adding!

**Comment by tylerreckart** [comment]
@bnb Awesome! I'll create a PR and get it sent off to you

**Comment by tylerreckart** [comment]
Closed for merged PR
